- url: 'https://github.com/PilzDE/pilz_robots/issues/128'
  title: 'timeout of test: prbt_hardware_support/integrationtest_brake_test_required'
  body: "### Commit\r\nhttps://github.com/PilzDE/pilz_robots/tree/d653264b47adb1c2fbe50e271d21ba8d1c625b8d\r\n\r\n### Steps to reproduce\r\nHow can the issue/bug be reproduced?\r\n1. Build Tests\r\n2. `rostest prbt_hardware_support integrationtest_brake_test_required.test`\r\n\r\n### Expected behavior\r\nTest exits successfully\r\n\r\n### Observed behavior\r\nTest times out\r\n\r\n### Logfiles\r\n```\r\n[ERROR] [1557999024.967094805]: Could not establish modbus connection.Connection refused\r\n[ERROR] [1557999024.967725786]: Init failed\r\n[ERROR] [1557999024.967743168]: Connection to 127.0.0.1:20701 failed. Try(1/10)\r\n[ERROR] [1557999024.994180516]: Waiting for Node /pilz_modbus_read_client_node\r\n[ERROR] [1557999024.994943383]: Notify\r\n[ERROR] [1557999024.994962549]: Inside Loop\r\n[ERROR] [1557999024.995308584]: Node /pilz_modbus_read_client_node found\r\n[ERROR] [1557999024.995327362]: Waiting for Node /modbus_brake_test_announcer_node\r\n[ERROR] [1557999024.995728553]: Node /modbus_brake_test_announcer_node found\r\n[ERROR] [1557999025.968288826]: modbus_tcp_accept\r\nERROR Connection reset by peer: read\r\n[Testcase: testintegrationtest_brake_test_required] ... ERROR!\r\nERROR: max time [60.0s] allotted for test [integrationtest_brake_test_required] of type [prbt_hardware_support/integrationtest_brake_test_required]\r\n  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\r\n    testMethod()\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rostest/runner.py\", line 148, in fn\r\n    self.test_parent.run_test(test)\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/rostest/rostest_parent.py\", line 132, in run_test\r\n    return self.runner.run_test(test)\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/launch.py\", line 689, in run_test\r\n    (test.time_limit, test.test_name, test.package, test.type))\r\n--------------------------------------------------------------------------------\r\n\r\n[ROSTEST]-----------------------------------------------------------------------\r\n\r\n```\r\n\r\n### Reference to test\r\n`rostest prbt_hardware_support integrationtest_brake_test_required.test`\r\n"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/pull/126'
  title: drop rviz exec_depend from prbt_support
  body: "To avoid GUI-dependencies in non-Gui-packages. `prbt_support` is installable on embedded hardware and should not draw in GUI-programs.\r\n\r\nOpen for discussion / My proposal:\r\n\r\n- [x] The launch file `test_urdf.launch` requires RVIZ. ~~Should it be moved into `prbt_moveit_config`? Or a note in Readme.md that RViZ is recommended but not strictly required and auto-installed?~~ I've moved it into the tests directory so that is no longer installed and excluded from `roslaunch_add_file_check`\r\n- [x] acceptance-tests (gripper and tcp) use RViz via test_urdf.launch. ~~Maybe a reference that RViZ has to be installed should be added there?~~ RViZ is now listed as `<test_depend>`."
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/pull/106'
  title: cleanup CMakeLists of prbt_hardware_support
  body: "Fixes #105\r\n* no library is built, so drop the export\r\n* pilz_testutils is only declared as test_depend, so move the\r\n  find_package call into the testing section"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/issues/93'
  title: 'CAN Error SAFE_TORQUE_OFF (ER: 129)'
  body: "\r\n\r\n### Commit\r\nUbuntu 18.04 using ROS melodic.\r\n\r\n### Steps to reproduce\r\nHow can the issue/bug be reproduced?\r\n1. Start the robot with holding the Enabling switch\r\n2. Release the switch, press it again, release it, ..... \r\n3. The Error will occur and the brakes won't open again after a few (sometimes even after the first) releases of the switch\r\n4. If I don't release the button (or in my case close and lock the door of the cell in automatic mode) the error won't occur as often as with the other tactic.\r\n\r\n### Expected behavior\r\nI expected, that the robot will continue working after the enabling switch is pressed again.\r\n\r\n### Observed behavior\r\nAfter Error I have to reboot the program (not the robot) to make it work again\r\n\r\n### Logfiles\r\nCAN Log:\r\n[candump-2019-03-27_105509.log](https://github.com/PilzDE/pilz_robots/files/3012949/candump-2019-03-27_105509.log)\r\n\r\nConsole Log:\r\n[Terminal output.txt](https://github.com/PilzDE/pilz_robots/files/3012956/Terminal.output.txt)\r\n\r\n\r\n"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/issues/92'
  title: >-
    Robot cannot be moved after Emergency-Stop/Panic button/ Enabling button
    release
  body: "### Commit (Stand: 19.03.2019):\r\n- kinetic-devel\r\n- pilz_industrial_motion - Version: 0.3.6-0\r\n- pilz_robots -  Version: 0.4.7-0\r\n- prbt_grippers - Version: 0.0.1-0\r\n\r\n### Steps to reproduce\r\nStart real robot via:  \r\n```roslaunch prbt_moveit_config moveit_planning_execution.launch sim:=false pipeline:=pilz_command_planner```\r\n1. Perform motion (e.g. vial Python script)\r\n2. During motion do one of the following things:\r\n    - release Enabling button,\r\n    - bush panic button or\r\n    - push emergency button.\r\n3. If no problem occures go back to step 1.\r\n\r\n### Expected behavior\r\nAfter I do one of the following things it should be possible to continue to move the robot:  \r\n- release Enabling button,\r\n- bush panic button or\r\n- push emergency button.\r\n\r\n### Observed behavior\r\nIt is not possible to continue to move the robot because on the console it is stated that:\r\n```PATH_TOLERANCE_VIOLATED```\r\n"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
    - medium
- url: 'https://github.com/PilzDE/pilz_robots/pull/87'
  title: Add missing dependency on joint_state_controller
  body: Also remove some redundant dependencies.
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/issues/83'
  title: Re-generate ikfast plugin
  body: "### Commit\r\n3efae68\r\n\r\n### Steps to reproduce\r\nHow can the issue/bug be reproduced?\r\n1. `roslaunch prbt_moveit_config moveit_planning_execution.launch`\r\n\r\n### Expected behavior\r\nNo warnings appear.\r\n\r\n### Observed behavior\r\nLog output:\r\n```\r\n[ WARN] [1552987873.840199096]: Kinematics solver doesn't support #attempts anymore, but only a timeout.\r\nPlease remove the parameter '/rviz_ROS_PC_6811_9210959308488888664/manipulator/kinematics_solver_attempts' from your configuration.\r\n[ WARN] [1552987873.848169752]: IK plugin for group 'manipulator' relies on deprecated API. Please implement initialize(RobotModel, ...).\r\n```\r\n\r\n### Reference to test\r\nMaybe a test checking for warning in /rosout during normal launch would help?\r\n\r\nThe fix should be as easy as re-generating the plugin from the current moveit master (see [moveit commit f19e411](https://github.com/ros-planning/moveit/commit/f19e411f2c4464783fd3994e6d3f6600adca7c91#diff-c0919d8a62d0d141b12acc2bf76ba7ed)\r\n\r\nRelated to #44  (hotfix)"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/issues/82'
  title: 'A3 joint limit violation in transport position '
  body: "Hi gentlemen,\r\n\r\nwhen I set the robot to the transport position it always shows a joint violation error. I made a test for each axis and find the axis A3 cannot set to -135 degree. However -134 is ok. Here is the code I write:\r\n\r\nhttps://github.com/yzhyff/prbt_training_cell/blob/1fccbda495a618bdb712919f4f61d94ff2c2f297/prbt_training_cell/scripts/transport.py#L1\r\n\r\n      "
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/issues/81'
  title: Modbus Timeout kills launch process
  body: "### Commit\r\n 05d7a01 \r\n\r\n### Steps to reproduce\r\nStart launch file on low-end pc with a large robot model. If the startup process takes more than 5 seconds, the modbus node dies.\r\n\r\n### Expected behavior\r\nNode waits until ROS is ready. There should not be a timeout at all, but just a warning to notify the user: \"Service xxx not yet available, waiting...\".\r\n\r\n### Observed behavior\r\nModbus node dies and takes down ROS.\r\n\r\n### Logfiles\r\n\r\n```\r\n[ INFO] [1552301651.010005889]: waitForService: Service [/prbt/manipulator_joint_trajectory_controller/hold] has not been advertised, waiting...\r\nprocess[usb_cam-11]: started with pid [4544]\r\nprocess[aruco_detect-12]: started with pid [4551]\r\nprocess[ref_fid_publisher-13]: started with pid [4553]\r\nprocess[fiducial_tf_converter-14]: started with pid [4567]\r\n[ INFO] [1552301651.281068524]: Loading robot model 'prbt'...\r\n[ WARN] [1552301651.281614825]: Skipping virtual joint 'FixedBase' because its child frame 'prbt_base_link' does not match the URDF frame 'base'\r\n[ INFO] [1552301651.281992211]: No root/virtual joint specified in SRDF. Assuming fixed joint\r\n[ INFO] [1552301651.980708962]: rviz version 1.12.16\r\n[ INFO] [1552301651.980808438]: compiled against Qt version 5.5.1\r\n[ INFO] [1552301651.980838067]: compiled against OGRE version 1.9.0 (Ghadamon)\r\n[ INFO] [1552301652.355542478]: Using fixed control period: 0.010000000\r\n[ INFO] [1552301652.587717879]: Initializing XXX\r\n[ INFO] [1552301652.588118552]: Current state: 1 device error: system:0 internal_error: 0 (OK)\r\n[ INFO] [1552301652.588401682]: Current state: 2 device error: system:0 internal_error: 0 (OK)\r\nEMCY: 83#0090212500000044\r\nEMCY: 84#0090212500000044\r\nEMCY: 85#0090212500000044\r\n[ INFO] [1552301652.812759987]: Stereo is NOT SUPPORTED\r\n[ INFO] [1552301652.813402492]: OpenGl version: 3 (GLSL 1.3).\r\nEMCY: 86#0090212500000044\r\nEMCY: 87#0090212500000044\r\nEMCY: 88#0090212500000044\r\nER: 33\r\n[ INFO] [1552301653.775363515]: Current state: 2 device error: system:125 internal_error: 0 (OK)\r\n[ INFO] [1552301653.775458465]: Current state: 1 device error: system:125 internal_error: 0 (OK)\r\n[ INFO] [1552301653.775812399]: Current state: 1 device error: system:0 internal_error: 0 (OK)\r\n[ INFO] [1552301653.775892800]: Current state: 0 device error: system:0 internal_error: 0 (OK)\r\n[ INFO] [1552301653.775944583]: Current state: 0 device error: system:0 internal_error: 0 (OK)\r\n[robot_init-6] process has finished cleanly\r\nlog file: /home/jgruner/.ros/log/f8ab4628-43eb-11e9-a364-8439be69721c/robot_init-6*.log\r\n[ INFO] [1552301654.292010270]: Publishing maintained planning scene on 'monitored_planning_scene'\r\n[ INFO] [1552301654.310662849]: MoveGroup debug mode is OFF\r\nStarting context monitors...\r\n[ INFO] [1552301654.310756724]: Starting scene monitor\r\n[ INFO] [1552301654.333239512]: Listening to '/planning_scene'\r\n[ INFO] [1552301654.333345179]: Starting world geometry monitor\r\n[ INFO] [1552301654.356504353]: Listening to '/collision_object' using message notifier with target frame '/base '\r\n[ INFO] [1552301654.373932880]: Listening to '/planning_scene_world' for planning scene world geometry\r\n[ INFO] [1552301654.976778466]: Listening to '/attached_collision_object' for attached collision objects\r\nContext monitors started.\r\n[ INFO] [1552301654.993191516]: Reading limits from namespace /robot_description_planning\r\n[ INFO] [1552301655.173408541]: Available plugins: pilz::PlanningContextLoaderCIRC pilz::PlanningContextLoaderLIN pilz::PlanningContextLoaderPTP \r\n[ INFO] [1552301655.173500376]: About to load: pilz::PlanningContextLoaderCIRC\r\n[ INFO] [1552301655.177550915]: Registered Algorithm [CIRC]\r\n[ INFO] [1552301655.178015249]: About to load: pilz::PlanningContextLoaderLIN\r\n[ INFO] [1552301655.190567122]: Registered Algorithm [LIN]\r\n[ INFO] [1552301655.190657450]: About to load: pilz::PlanningContextLoaderPTP\r\n[ INFO] [1552301655.199674187]: Registered Algorithm [PTP]\r\n[ INFO] [1552301655.200266448]: Using planning interface 'Simple Command Planner'\r\nterminate called after throwing an instance of 'prbt_hardware_support::PilzStoModbusAdapterNodeException'\r\n  what():  Controller service manipulator_joint_trajectory_controller/hold not available. STO adapter node can not function properly. Shutting down ROS ...\r\n================================================================================REQUIRED process [prbt/sto_modbus_adapter_node-8] has died!\r\nprocess has died [pid 4510, exit code -6, cmd /opt/ros/kinetic/lib/prbt_hardware_support/sto_modbus_adapter_node __name:=sto_modbus_adapter_node __log:=/home/jgruner/.ros/log/f8ab4628-43eb-11e9-a364-8439be69721c/prbt-sto_modbus_adapter_node-8.log].\r\nlog file: /home/jgruner/.ros/log/f8ab4628-43eb-11e9-a364-8439be69721c/prbt-sto_modbus_adapter_node-8*.log\r\nInitiating shutdown!\r\n================================================================================\r\n```"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/issues/70'
  title: Gazebo integrationtest errors
  body: "### Commit\r\n93454eb1c7e1fe3e46ec47d8d778d73d68722161\r\n\r\n### Steps to reproduce\r\nThis happened here: https://travis-ci.org/PilzDE/pilz_robots/jobs/492676506\r\nI do not know, how to reproduce it.\r\n\r\n### Log\r\n\r\n> [ INFO] [1550063952.451245135]: Loading robot model 'prbt'...\r\n[ WARN] [1550063952.451764145]: Skipping virtual joint 'FixedBase' because its child frame 'prbt_base_link' does not match the URDF frame 'world'\r\n[ INFO] [1550063952.452015314]: No root/virtual joint specified in SRDF. Assuming fixed joint\r\n[ INFO] [1550063953.094379308]: Finished loading Gazebo ROS API Plugin.\r\n[ INFO] [1550063953.107568358]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...\r\n[ INFO] [1550063953.189882115]: Publishing maintained planning scene on 'monitored_planning_scene'\r\n[ INFO] [1550063953.231851913]: MoveGroup debug mode is OFF\r\nStarting context monitors...\r\n[ INFO] [1550063953.231918243]: Starting scene monitor\r\n[ INFO] [1550063953.278778984]: Listening to '/planning_scene'\r\n[ INFO] [1550063953.278831298]: Starting world geometry monitor\r\n[ INFO] [1550063953.325316757]: Listening to '/collision_object' using message notifier with target frame '/world '\r\n[ INFO] [1550063953.331388117]: Listening to '/planning_scene_world' for planning scene world geometry\r\n[ INFO] [1550063953.345524752]: Listening to '/attached_collision_object' for attached collision objects\r\nContext monitors started.\r\n[ INFO] [1550063953.391006143]: Initializing OMPL interface using ROS parameters\r\nSpawnModel script started\r\n[ INFO] [1550063953.452645766]: Using planning interface 'OMPL'\r\n[ INFO] [1550063953.471948682]: Param 'default_workspace_bounds' was not set. Using default value: 10\r\n[ INFO] [1550063953.473790777]: Param 'start_state_max_bounds_error' was set to 0.1\r\n[ INFO] [1550063953.475083585]: Param 'start_state_max_dt' was not set. Using default value: 0.5\r\n[ INFO] [1550063953.476805438]: Param 'start_state_max_dt' was not set. Using default value: 0.5\r\n[ INFO] [1550063953.478555325]: Param 'jiggle_fraction' was set to 0.05\r\n[ INFO] [1550063953.480034626]: Param 'max_sampling_attempts' was not set. Using default value: 100\r\n[ INFO] [1550063953.480121613]: Using planning request adapter 'Add Time Parameterization'\r\n[ INFO] [1550063953.480146465]: Using planning request adapter 'Fix Workspace Bounds'\r\n[ INFO] [1550063953.480170137]: Using planning request adapter 'Fix Start State Bounds'\r\n[ INFO] [1550063953.480196078]: Using planning request adapter 'Fix Start State In Collision'\r\n[ INFO] [1550063953.480210983]: Using planning request adapter 'Fix Start State Path Constraints'\r\n[INFO] [1550063953.545793, 0.000000]: Loading model XML from ros parameter\r\n[INFO] [1550063953.548924, 0.000000]: Waiting for service /gazebo/spawn_urdf_model\r\nError [parser.cc:581] Unable to find uri[model://sun]\r\nLoading 'move_group/ApplyPlanningSceneService'...\r\nLoading 'move_group/ClearOctomapService'...\r\nLoading 'move_group/MoveGroupCartesianPathService'...\r\nLoading 'move_group/MoveGroupExecuteTrajectoryAction'...\r\nLoading 'move_group/MoveGroupGetPlanningSceneService'...\r\nLoading 'move_group/MoveGroupKinematicsService'...\r\nLoading 'move_group/MoveGroupMoveAction'...\r\nLoading 'move_group/MoveGroupPickPlaceAction'...\r\nLoading 'move_group/MoveGroupPlanService'...\r\nLoading 'move_group/MoveGroupQueryPlannersService'...\r\nLoading 'move_group/MoveGroupStateValidationService'...\r\nYou can start planning now!\r\nTraceback (most recent call last):\r\n  File \"/opt/ros/kinetic/lib/gazebo_ros/spawn_model\", line 313, in <module>\r\n    sm.callSpawnService()\r\n  File \"/opt/ros/kinetic/lib/gazebo_ros/spawn_model\", line 271, in callSpawnService\r\n    initial_pose, self.reference_frame, self.gazebo_namespace)\r\n  File \"/opt/ros/kinetic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py\", line 28, in spawn_urdf_model_client\r\n    rospy.wait_for_service(gazebo_namespace+'/spawn_urdf_model')\r\n  File \"/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py\", line 159, in wait_for_service\r\n    raise ROSInterruptException(\"rospy shutdown\")\r\nrospy.exceptions.ROSInterruptException: rospy shutdown\r\n[WARN] [1550064013.559037, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.\r\n[Testcase: testintegrationtest_gazebo_bringup] ... ERROR!\r\nERROR: max time [60.0s] allotted for test [integrationtest_gazebo_bringup] of type [prbt_gazebo/integrationtest_gazebo_bringup]\r\n"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/issues/65'
  title: Start no possible because of unreasonable joint state
  body: "Error:\r\n```\r\nEMCY: 83#0000000000000000\r\nEMCY: 84#0000000000000000\r\nEMCY: 85#0000000000000000\r\nEMCY: 86#0000000000000000\r\nEMCY: 87#0000000000000000\r\nEMCY: 88#0000000000000000\r\n[robot_init-6] process has finished cleanly\r\nlog file: ~/.ros/log/7961ebfc-e1a7-11e8-b4cf-b7756f5a66b8/robot_init-6*.log\r\nEMCY: 88#008421E4C1E8F5C7\r\n[ERROR] [1541497011.749882349]: Node has emergency error\r\n```\r\n\r\nAngle:\r\n```\r\nheader: \r\n  seq: 1094\r\n  stamp: \r\n    secs: 1541497033\r\n    nsecs: 572782638\r\n  frame_id: ''\r\nname: [prbt_joint_1, prbt_joint_2, prbt_joint_3, prbt_joint_4, prbt_joint_5, prbt_joint_6]\r\nposition: [-0.025691246589356526, -0.41233403578366035, 0.7356039198380501, -0.001902408884673819, 1.9980005678055484, 15.406073667231507]\r\nvelocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]\r\neffort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]\r\n```"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/pull/62'
  title: 'Remove exec_depend on metapackages Closes #61'
  body: '  * Cleanup deps'
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/issues/61'
  title: Do not depend on meta-package(s)
  body: "prbt_moveit_config depends on ros_control and on ros_controllers, but according to [REP-140](http://www.ros.org/reps/rep-0140.html#metapackage) this is not allowed (see discussion in https://github.com/catkin/catkin_tools/issues/370)\r\n\r\nFor me the current situation causes error outputs of catkin build:\r\n```\r\nAbandoned <<< prbt_gazebo                                   [ Depends on unknown jobs: ros_control ]                                     \r\nAbandoned <<< prbt_moveit_config                            [ Depends on unknown jobs: ros_control ] \r\n```\r\nand in some (not reproducible) situation @JonathanGruner experienced an error in the first step of `catkin_make` so that the build failed completely."
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/pull/57'
  title: Add missing <build_depend> on roscpp
  body: >-
    Needed since binary jobs are failing on the buildfarm due to missing
    <build_depend>
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/issues/53'
  title: Gazebo crashes at start up
  body: "Up to commit eb203fdbc63503d53c2cfe956dc2a1c0d5fb7470 Gazebo starts without problems. From commit 71bf950fc0a6fdacca01faf0239f43ab1a8eb299 forth Gazebo  immediately crashes at start-up. The only information I get on the terminal is:\r\n\r\n`[gazebo_gui-3] process has died [pid 31572, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/hslusarek/.ros/log/b9a1d926-17fc-11e9-a60e-1866da344b68/gazebo_gui-3.log].\r\nlog file: /home/hslusarek/.ros/log/b9a1d926-17fc-11e9-a60e-1866da344b68/gazebo_gui-3*.log\r\n`\r\nwhich basically says nothing. However, the problem seems be the mesh file change for link 5."
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
- url: 'https://github.com/PilzDE/pilz_robots/pull/47'
  title: add dependency moveit_config->prbt_ikfast
  body: "The launch files in moveit_config set the ikfast plugin as kinematics solver\r\nso adding a depend to install the package."
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels: []
- url: 'https://github.com/PilzDE/pilz_robots/issues/44'
  title: IKfast plugin uses deprecated plugin API
  body: "See: https://github.com/ros-planning/moveit/issues/1262\r\n\r\nThis leads to a build failure on our side: (on **melodic-devel**)\r\n\r\n> pilz_robots/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp:\r\n\r\n> In member function ‘virtual bool ikfast_kinematics_plugin::IKFastKinematicsPlugin::initialize(const string&, const string&, const string&, const string&, double)’:\r\npilz_robots/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp:343:86: error: ‘virtual void kinematics::KinematicsBase::setValues(const string&, const string&, const string&, const string&, double)’ is deprecated [-Werror=deprecated-declarations]\r\n   setValues(robot_description, group_name, base_name, tip_name, search_discretization);\r\n"
  repo: 'https://api.github.com/repos/PilzDE/pilz_robots'
  labels:
    - bug
